import { json } from "./fs.js";
import type { EmittedPluginConfig, FileValue } from "./types.js";

/** Output-relative path of the generated update-check script within a plugin. */
export const UPDATE_CHECK_SCRIPT_PATH = "scripts/pluginpack-update-check.sh";
/** Output-relative path of a plugin's hooks registration file. */
export const HOOKS_FILE_PATH = "hooks/hooks.json";

// The marker every generated command contains; merge is idempotent on it, so a
// re-run (or a source plugin that already wired the script) never appends twice.
const SCRIPT_MARKER = "pluginpack-update-check";

export type UpdateCheckFormat = "claude" | "cursor";

export type UpdateCheckOptions = {
  format: UpdateCheckFormat;
  pluginName: string;
  version: string;
  repository: string;
};

/**
 * The per-plugin opt-out gate, shared by both call sites that decide whether
 * this plugin gets the generated hook (file injection in
 * `src/targets/engine.ts`'s `emitFromDefinition`, and each target's own
 * `buildPluginManifest` for the manifest's `hooks` pointer) — callers still
 * check their own target-level `updateCheck` presence first, for
 * type-narrowing convenience.
 */
export function pluginAllowsUpdateCheck(
  pluginConfig: Pick<EmittedPluginConfig, "updateCheck">,
): boolean {
  return pluginConfig.updateCheck !== false;
}

// POSIX single-quote: close, escaped quote, reopen.
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

// Escape a value for interpolation into a printf format string ("%" is the
// only metacharacter) that is then JSON-string-escaped as a whole.
function printfEscape(value: string): string {
  return value.replaceAll("%", "%%");
}

// Everything that varies by target format, in one place — adding a third
// format means adding one entry here, not hunting down every `=== "claude"`.
type FormatConfig = {
  mergeHooks: (existing: string | undefined) => string;
  // Shell expression supplying printf's args, in the order this format's
  // payload() below expects them (claude: latest, installed; cursor: the reverse).
  nudgeArgs: string;
  // The nudge payload with printf's two %s slots left as literal placeholders.
  payload: (name: string) => Record<string, string>;
};

const FORMATS: Record<UpdateCheckFormat, FormatConfig> = {
  claude: {
    mergeHooks: mergeClaudeHooks,
    nudgeArgs: '"$latest" "$INSTALLED"',
    // systemMessage is shown directly to the user by Claude Code.
    payload: (name) => ({
      systemMessage: `Plugin ${name} v%s is available (installed v%s). Run /plugin update ${name} to upgrade.`,
    }),
  },
  cursor: {
    mergeHooks: mergeCursorHooks,
    nudgeArgs: '"$INSTALLED" "$latest"',
    // Cursor's sessionStart hook has no user-visible output; ask the agent to relay it.
    payload: (name) => ({
      additional_context: `The installed Cursor plugin "${name}" is outdated (installed v%s, latest v%s). Briefly let the user know they can update it from Cursor's plugin settings.`,
    }),
  },
};

// The nudge is a printf format string: JSON payload with two %s slots, plus a
// trailing newline. printf interprets backslash escapes in its format string,
// so JSON's own escapes (e.g. \") must be doubled to survive, while the
// appended \n is left single so printf renders the newline.
function nudgeFormat(format: UpdateCheckFormat, pluginName: string): string {
  const payload = FORMATS[format].payload(printfEscape(pluginName));
  const literal = JSON.stringify(payload).replaceAll("\\", "\\\\");
  return shellQuote(`${literal}\\n`);
}

/** Renders the POSIX-sh update-check script embedded into a plugin, for the given format. */
export function renderUpdateCheckScript(options: UpdateCheckOptions): string {
  const { format, pluginName, version, repository } = options;
  const nudgeArgs = FORMATS[format].nudgeArgs;
  return `#!/bin/sh
# Generated by pluginpack — session-start update check for ${JSON.stringify(pluginName)}.
# Compares the installed version against the latest git tag of the plugin repo,
# throttled to one network check per 24h (cache shared across plugins from the
# same repo). Fail-open by design: any problem exits 0 with no output.
[ "\${PLUGINPACK_NO_UPDATE_CHECK:-}" = "1" ] && exit 0
[ -n "\${CI:-}" ] && exit 0
command -v git >/dev/null 2>&1 || exit 0

INSTALLED=${shellQuote(version)}
REPO_URL=${shellQuote(repository)}

# Only plain dotted-numeric versions compare meaningfully with sort below.
case "$INSTALLED" in
  "" | *[!0-9.]* | .* | *.) exit 0 ;;
esac

CACHE_DIR="\${XDG_CACHE_HOME:-$HOME/.cache}/pluginpack"
KEY=$(printf '%s' "$REPO_URL" | cksum | cut -d ' ' -f 1) || exit 0
CACHE_FILE="$CACHE_DIR/latest-$KEY"
now=$(date +%s) || exit 0
latest=""
cached_at=0
if [ -f "$CACHE_FILE" ]; then
  read -r cached_at latest <"$CACHE_FILE" || true
fi
case "$cached_at" in
  "" | *[!0-9]*) cached_at=0 ;;
esac
if [ $((now - cached_at)) -ge 86400 ]; then
  mkdir -p "$CACHE_DIR" 2>/dev/null || exit 0
  # Timestamp sentinel before fetching, so sibling plugins don't race-fetch.
  printf '%s %s\\n' "$now" "" >"$CACHE_FILE" 2>/dev/null || true
  tags=$(GIT_TERMINAL_PROMPT=0 git -c http.connectTimeout=5 \\
    -c http.lowSpeedLimit=1000 -c http.lowSpeedTime=10 \\
    ls-remote --tags --refs "$REPO_URL" 2>/dev/null) || exit 0
  # Highest stable semver tag; "v" prefix tolerated, prereleases ignored.
  latest=$(printf '%s\\n' "$tags" |
    sed -n 's#.*refs/tags/v\\{0,1\\}\\([0-9][0-9]*\\.[0-9][0-9]*\\.[0-9][0-9]*\\)$#\\1#p' |
    sort -t . -k 1,1n -k 2,2n -k 3,3n | tail -n 1)
  printf '%s %s\\n' "$now" "$latest" >"$CACHE_FILE" 2>/dev/null || true
fi
[ -n "$latest" ] || exit 0
[ "$latest" = "$INSTALLED" ] && exit 0
newest=$(printf '%s\\n%s\\n' "$INSTALLED" "$latest" |
  sort -t . -k 1,1n -k 2,2n -k 3,3n | tail -n 1)
[ "$newest" = "$latest" ] || exit 0
printf ${nudgeFormat(format, pluginName)} ${nudgeArgs}
exit 0
`;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

// Parse an existing hooks.json and hand back the object plus the event array to
// append to, enforcing the shapes both hosts expect. Throws bare reasons; the
// caller wraps them with target/plugin context.
function parseHooksFile(
  existing: string,
  eventName: string,
): { root: Record<string, unknown>; events: unknown[] } {
  let root: unknown;
  try {
    root = JSON.parse(existing);
  } catch {
    throw new Error("not valid JSON");
  }
  if (!isPlainObject(root)) {
    throw new Error("must be a JSON object");
  }
  const hooks = root.hooks ?? {};
  if (!isPlainObject(hooks)) {
    throw new Error('"hooks" must be an object');
  }
  const events = hooks[eventName] ?? [];
  if (!Array.isArray(events)) {
    throw new Error(`"hooks.${eventName}" must be an array`);
  }
  root.hooks = hooks;
  hooks[eventName] = events;
  return { root, events };
}

/** Merges the update-check hook into an existing (or new) Claude `hooks/hooks.json`. */
export function mergeClaudeHooks(existing: string | undefined): string {
  if (existing?.includes(SCRIPT_MARKER)) {
    return existing;
  }
  const { root, events } = parseHooksFile(existing ?? "{}", "SessionStart");
  events.push({
    matcher: "startup|resume",
    hooks: [
      {
        type: "command",
        command: `sh "\${CLAUDE_PLUGIN_ROOT}/${UPDATE_CHECK_SCRIPT_PATH}"`,
        timeout: 15,
      },
    ],
  });
  return json(root);
}

/** Merges the update-check hook into an existing (or new) Cursor `hooks/hooks.json`. */
export function mergeCursorHooks(existing: string | undefined): string {
  if (existing?.includes(SCRIPT_MARKER)) {
    return existing;
  }
  const { root, events } = parseHooksFile(
    existing ?? '{ "version": 1 }',
    "sessionStart",
  );
  root.version ??= 1;
  events.push({
    command: `sh ./${UPDATE_CHECK_SCRIPT_PATH}`,
    timeout: 15,
  });
  return json(root);
}

/**
 * Injects the generated script and hook registration into a plugin's
 * collected files (paths relative to the plugin root), merging with a
 * source-authored `hooks/hooks.json` when present.
 */
export function applyUpdateCheck(
  pluginFiles: Map<string, FileValue>,
  target: string,
  options: UpdateCheckOptions,
): void {
  if (pluginFiles.has(UPDATE_CHECK_SCRIPT_PATH)) {
    throw new Error(
      `Target "${target}" plugin "${options.pluginName}" already contains ` +
        `"${UPDATE_CHECK_SCRIPT_PATH}", which collides with the generated update-check script.`,
    );
  }
  const existingValue = pluginFiles.get(HOOKS_FILE_PATH);
  const existing =
    existingValue === undefined
      ? undefined
      : typeof existingValue === "string"
        ? existingValue
        : existingValue.toString("utf8");
  let merged: string;
  try {
    merged = FORMATS[options.format].mergeHooks(existing);
  } catch (error) {
    throw new Error(
      `Target "${target}" plugin "${options.pluginName}" has an invalid ` +
        `"${HOOKS_FILE_PATH}" (${error instanceof Error ? error.message : String(error)}); ` +
        `cannot merge the generated update-check hook.`,
      { cause: error },
    );
  }
  pluginFiles.set(HOOKS_FILE_PATH, merged);
  pluginFiles.set(UPDATE_CHECK_SCRIPT_PATH, renderUpdateCheckScript(options));
}
